# Generated by Django 5.0 on 2024-01-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NEWS', '0002_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dataCreation',
            new_name='dateCreation',
        ),
    ]
