# Generated by Django 5.0 on 2024-01-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NEWS', '0003_rename_datacreation_post_datecreation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dateCreation',
            new_name='dataCreation',
        ),
    ]
